### ISSUE TITLE
case top cover and transfluent one

### ISSUE THREAD

**Issue by serperus** [cristianoag/trhmsx#1]
Hi Cristiano!
Thanks for the great project :)
Could you please look at the cover for 3d printing? Seems the cart slot is a bit out of place.

Thanks!
![trhmsxcart](https://github.com/user-attachments/assets/22906de0-e04b-488b-b262-074c6de6d7e8)

**Comment by cristianoag** [comment]
Hi @serperus, I've cut that cover with my laser multiple times without any issues. Could you clarify what you mean by "out of place"?

**Comment by cristianoag** [comment]
I just cut another piece on the laser, and that part measures 11mm, not 6.5mm. I also double-checked the project file, and it’s correct. It might be a conversion issue between inches and centimeters.
![image](https://github.com/user-attachments/assets/e0f2eb6e-8aef-4d96-be98-fe20f09369f4)

**Comment by serperus** [comment]
Hi Cristiano,
Yes, yor measurement is correct.
Printed this cover:

https://github.com/cristianoag/trhmsx/blob/main/case/TRHMSX_Translucent_Cover.stl at jlc3d and got 6,5mm where you have 11mm.

![image](https://github.com/user-attachments/assets/895592f3-b8da-432f-9b57-494a02ebfa34)
![image](https://github.com/user-attachments/assets/cbb34b99-40d9-4c16-ae26-2865ec49c4aa)

Have no idea what goes wrong.
Thank you
Serge

**Comment by cristianoag** [comment]
Got it. Yeah, my fault.. sorry. I usually cut that cover in transparent acrylic and for that I use LightBurn and the .lbrn2 file. Just fixed the cover. Sorry... you will need to print it again. :( I recommend doing that with translucent filament or transparent resin.

**Comment by serperus** [comment]
It's ok, will print it once more. 
Thank you!
